export const speciesConfig = {
  HERB: {
    start: 28,
    baseSpeed: 0.55,
    hungerRate: 0.015,           // Energía perdida por segundo
    vision: 6,
    preyEnergy: 0.9,
    fecundity: 1.6,
    size: 'medium',
    lifespan: 200,
    reproThreshold: 1.6,         // Energía mínima para reproducirse
    reproCost: 0.8,
    reproCooldown: 5,
    nightSpeedMul: 0.9,
    nightVisionMul: 0.9,
    maxEnergy: 2.5,
    radius: 0.32,
    initEnergy: 1.0,
    addEnergy: 1.0,
    offspringEnergy: 0.8,
    wanderFactor: 2.0,
    diet: { PLANT: { energy: 0.18, plantDelta: 0.22 } }
  },
  CARN: {
    start: 10,
    baseSpeed: 0.7,
    hungerRate: 0.02,
    vision: 9,
    preyEnergy: 1.2,
    fecundity: 2.2,
    size: 'medium',
    lifespan: 220,
    reproThreshold: 2.2,
    reproCost: 1.1,
    reproCooldown: 7,
    nightSpeedMul: 1.1,
    nightVisionMul: 1.1,
    radius: 0.36,
    initEnergy: 1.4,
    addEnergy: 1.2,
    offspringEnergy: 1.0,
    wanderFactor: 1.3,
    diet: { HERB: true }
  },
  RODENT: {
    start: 12,
    baseSpeed: 0.5,
    hungerRate: 0.02,
    vision: 5,
    preyEnergy: 0.8,
    fecundity: 1.2,
    size: 'small',
    lifespan: 180,
    reproThreshold: 1.2,
    reproCost: 0.6,
    reproCooldown: 5,
    nightSpeedMul: 0.9,
    nightVisionMul: 0.9,
    radius: 0.3,
    initEnergy: 0.9,
    offspringEnergy: 0.7,
    wanderFactor: 2.0,
    diet: { PLANT: { energy: 0.15, plantDelta: 0.2 } }
  },
  WOLF: {
    start: 4,
    baseSpeed: 0.8,
    hungerRate: 0.025,
    vision: 10,
    preyEnergy: 1.5,
    fecundity: 2.4,
    size: 'large',
    lifespan: 240,
    reproThreshold: 2.4,
    reproCost: 1.2,
    reproCooldown: 7,
    nightSpeedMul: 1.1,
    nightVisionMul: 1.1,
    radius: 0.38,
    initEnergy: 1.5,
    offspringEnergy: 1.1,
    wanderFactor: 1.3,
    diet: { HERB: true, RODENT: true }
  },
  POLLINATOR: {
    start: 16,
    baseSpeed: 0.5,
    hungerRate: 0.01,
    vision: 4,
    preyEnergy: 0.5,
    fecundity: 1.0,
    size: 'small',
    lifespan: 160,
    reproThreshold: 1.0,
    reproCost: 0.5,
    reproCooldown: 5,
    nightSpeedMul: 1.0,
    nightVisionMul: 1.0,
    radius: 0.28,
    initEnergy: 0.8,
    offspringEnergy: 0.6,
    wanderFactor: 2.0,
    diet: { PLANT: { energy: 0.05, plantDelta: 0.005 } }
  }
};
